export const OPENSKY_CONSTANTS = {
  AUTH: {
    USERNAME: process.env.OPEN_SKY_USER || '',
    PASSWORD: process.env.OPEN_SKY_PASS || '',
  },

  RATE_LIMITS: {
    ANONYMOUS: {
      REQUESTS_PER_MINUTE: 100,
      REQUESTS_PER_10_MIN: 300,
      REQUESTS_PER_DAY: 10000,
      BATCH_SIZE: 25,
      MIN_INTERVAL: 5000,
      MAX_CONCURRENT: 2,
    },

  AUTHENTICATED: {
      REQUESTS_PER_MINUTE: 100,
      REQUESTS_PER_10_MIN: 600,
      REQUESTS_PER_DAY: 50000,
      MAX_BATCH_SIZE: 100,
      MIN_INTERVAL: 1000,
      MAX_CONCURRENT: 5,
      MAX_ICAO_QUERY: 500,
      MAX_TOTAL_ICAO_QUERY: 1000,
      MAX_RETRY_LIMIT: 5,
    }
  },

  TIME_WINDOWS: {
    TEN_MINUTES_MS: 10 * 60 * 1000,
    ONE_DAY_MS: 24 * 60 * 60 * 1000,
  },
    
}
