export const PARSER_CONSTANTS = {
  INDICES: {
    ICAO24: 0,
    CALLSIGN: 1,
    ORIGIN_COUNTRY: 2,
    TIME_POSITION: 3,
    LAST_CONTACT: 4,
    LONGITUDE: 5,
    LATITUDE: 6,
    BARO_ALTITUDE: 7,
    ON_GROUND: 8,
    VELOCITY: 9,
    TRUE_TRACK: 10,
    VERTICAL_RATE: 11,
    SENSORS: 12,
    GEO_ALTITUDE: 13,
    SQUAWK: 14,
    SPI: 15,
    POSITION_SOURCE: 16
  },
  DEFAULT_VALUES: {
    ALTITUDE: 0,
    VELOCITY: 0,
    HEADING: 0,
    VERTICAL_RATE: 0
  }
} as const;