// src/config/rate-limits.ts
export const RATE_LIMITS = {
  ANONYMOUS: {
    REQUESTS_PER_MINUTE: 50,
    REQUESTS_PER_10_MIN:100,
    REQUESTS_PER_DAY: 10000,
    BATCH_SIZE: 25,
    MIN_INTERVAL: 5000,
    MAX_CONCURRENT: 2,
  },
  AUTHENTICATED: {
    REQUESTS_PER_MINUTE: 100,
    REQUESTS_PER_10_MIN:300,
    REQUESTS_PER_DAY: 50000,
    BATCH_SIZE: 100,
    MIN_INTERVAL: 1000,
    MAX_CONCURRENT: 5,
    MAX_RETRY_LIMIT: 5,
    MAX_WAIT_TIME:20000
  },
} as const;